[package]
name = "scarf"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }
futures = "0.3.17"
rand = "0.8.4"
log = "0.4.0"
env_logger = "0.9.0"
